-- Deletar banco de dados
DROP DATABASE DB_LOJAABC;

-- Criar bano de dados
CREATE DATABASE DB_LOJAABC;

-- Acessar o banco de dados
USE DB_LOJAABC

-- Criar as tabelas


CREATE TABLE TB_FUNCIONARIOS(
	COD_FUNCIONARIO INT,
	CPF CHAR(14),
	NOME_FUNCIONARIO VARCHAR(100),
	EMAIL_FUNCIONARIO VARCHAR(100),
	TELEFONE CHAR(10),
	DATA_NASCIMENTO DATE,
	ENDERECO VARCHAR(100),
	NUMERO CHAR(10),
	CEP CHAR(10),
	BAIRRO CHAR(100),
	CIDADE VARCHAR(100),
	UF CHAR(02),
	SALARIO DECIMAL (9,2)

);

INSERT INTO TB_FUNCIONARIOS 
(COD_FUNCIONARIO, CPF           , NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, TELEFONE  , DATA_NASCIMENTO, ENDERECO    , NUMERO, CEP     , BAIRRO       , CIDADE, UF, SALARIO)
VALUES
(001           ,'000.000.000-00','JOAO DA SILVA','TESTE@GMAIL.COM'  , '0000-0000', '0000/00/00'   , 'RUA TESTE', '456' , '0000-000','SANTO AMARO', 'SAO PAULO', 'SP', 1500.00)



select * from TB_FUNCIONARIOS
