--DROP DATABASE DB_PORTARIA;

--DROP TABLE TB_FUNCIONARIOS;

CREATE DATABASE DB_PORTARIA;

USE DB_PORTARIA;


--CONSULTAS DAS TABELAS
SP_HELP TB_FUNCIONARIOS
SP_HELP TB_USUARIOS

SELECT*FROM TB_FUNCIONARIOS;
SELECT*FROM TB_USUARIOS;
SELECT*FROM TB_CLIENTES;
SELECT*FROM TB_FORNECEDORES;
SELECT*FROM TB_PRODUTOS;
SELECT*FROM TB_VENDAS;


--DELETE DE TABELAS

DROP TABLE TB_FUNCIONARIOS;
DROP TABLE TB_USUARIOS;
DROP TABLE TB_CLIENTES;
DROP TABLE TB_FORNECEDORES;
DROP TABLE TB_PRODUTOS;
DROP TABLE TB_VENDAS;



--CHAVE PRIMÁRIA:DADO ÚNICO PARA LIGAÇÃO COM OUTRAS TABELAS

CREATE TABLE TB_FUNCIONARIOS(
			COD_FUNCIONARIO   INT           NOT NULL IDENTITY(1,1),
			NOME              VARCHAR (100) NOT NULL,
			RG                CHAR(14)      NOT NULL,
			CPF               CHAR(13)      NOT NULL UNIQUE,
			SEXO              CHAR(1)       DEFAULT 'F' CHECK (SEXO IN ('F', 'M')),
			SALARIO           DECIMAL(9,2)  DEFAULT  0 CHECK (SALARIO >=0),
			
			PRIMARY KEY(COD_FUNCIONARIO)

)

INSERT INTO TB_FUNCIONARIOS (NOME,RG,CPF, SEXO, SALARIO) VALUES ('IVANA MATTOS','52.741.528-7','42578598577','F',  '2500.45');
INSERT INTO TB_FUNCIONARIOS (NOME,RG,CPF, SEXO, SALARIO) VALUES ('JOÃO CARLOS', '33.456.456-7', '3456989516', 'M', '3000.00');
INSERT INTO TB_FUNCIONARIOS (NOME,RG,CPF, SEXO, SALARIO) VALUES ('PEDRO JOSE', '44.555.999-8', '5687891255', 'M', '1800.00');
INSERT INTO TB_FUNCIONARIOS (NOME,RG,CPF, SEXO, SALARIO) VALUES ('AUGUSTO SANTOS', '28.369.222-4', '6558791551', 'M', '1800.00');


CREATE TABLE TB_USUARIOS(
			COD_USU      INT,
			NOME         VARCHAR(50) NOT NULL,
			SENHA        VARCHAR(20) NOT NULL,
			COD_FUNCIONARIO     INT NOT NULL,

			PRIMARY KEY (COD_USU),
			FOREIGN KEY (COD_FUNCIONARIO) REFERENCES TB_FUNCIONARIOS (COD_FUNCIONARIO)
		
)


INSERT INTO TB_USUARIOS (COD_USU, NOME, SENHA, COD_FUNCIONARIO) VALUES (1,'PEDRO.JOSE', '123456', 3);
INSERT INTO TB_USUARIOS (COD_USU, NOME, SENHA, COD_FUNCIONARIO) VALUES (2,'IVANA.MATTOS', '654987', 1);
INSERT INTO TB_USUARIOS (COD_USU, NOME, SENHA, COD_FUNCIONARIO) VALUES (3,'JOÃO.CARLOS', '444555', 2);
INSERT INTO TB_USUARIOS (COD_USU, NOME, SENHA, COD_FUNCIONARIO) VALUES (4,'AUGUSTO SANTOS', '568768', 6);

CREATE TABLE TB_CLIENTES(
			 COD_CLI     INT NOT NULL IDENTITY(1,1),
			 NOME        VARCHAR (50),
			 EMAIL       VARCHAR(50),
			 TEL_CEL     CHAR(10),
			 
			 PRIMARY KEY (COD_CLI)

)

INSERT INTO TB_CLIENTES(NOME, EMAIL, TEL_CEL) VALUES ('JOANA ANTUNES', 'JOANA.ANTUNES@GMAIL.COM', '989899853')
INSERT INTO TB_CLIENTES(NOME, EMAIL, TEL_CEL) VALUES ('KATIA ASSAD', 'KATIA.ASSAD@HOTMAIL.COM', '945693156')
INSERT INTO TB_CLIENTES(NOME, EMAIL, TEL_CEL) VALUES ('MAURICIO DE SOUZA', 'MAURICIO.SOUZA@HOTMAIL.COM', '944563315');
INSERT INTO TB_CLIENTES(NOME,EMAIL,TEL_CEL) VALUES ('DAVI SILVA', 'DAVI.SILVA@GMAIL.COM', '987779635');


CREATE TABLE TB_FORNECEDORES(
			COD_FORN INT NOT NULL IDENTITY(1,1),
			NOME     VARCHAR(100),
			EMAIL    VARCHAR(100),
			TELEFONE CHAR(10),
			CNPJ     CHAR(14) NOT NULL UNIQUE,
			
			PRIMARY KEY (COD_FORN)
);

INSERT INTO TB_FORNECEDORES(NOME, EMAIL, TELEFONE, CNPJ) VALUES ('ARMARINHOS FERNANDES', 'SAC@AFERNANDES@GMAIL.COM', '5566-4455', '48076228000604');
INSERT INTO TB_FORNECEDORES(NOME, EMAIL, TELEFONE, CNPJ) VALUES ('HORTIFRUTI FERNANDO', 'HORTIFRUTI.FERNANDO@GMAIL.COM', '4444-9898', '48474845000145');
INSERT INTO TB_FORNECEDORES(NOME, EMAIL, TELEFONE, CNPJ) VALUES ('ARMARINHO SÃO JOSÉ', 'ARMARINHOSJOSE@GMAIL.COM', '3335-9889', '48076228002801');
INSERT INTO TB_FORNECEDORES(NOME, EMAIL, TELEFONE, CNPJ) VALUES ('ATACADO JOÃO', 'ATACADAO.JOAO@GMAIL.COM', '4455-9889', '33223366597');


CREATE TABLE TB_PRODUTOS(
			COD_PROD       INT NOT NULL IDENTITY (1,1),
			DESRICAO       VARCHAR(100) NOT NULL,
			LOTE           CHAR (12),
			VALIDADE       DATE,
			DATA_ENTRADA   DATE,
			HORA_ENTRADA   TIME,
			QUANTIDADE     INT,
			PRECO          DECIMAL(9,2),
			COD_FORN       INT NOT NULL,

			PRIMARY KEY (COD_PROD),
			FOREIGN KEY (COD_FORN) REFERENCES TB_FORNECEDORES
)

INSERT INTO TB_PRODUTOS (DESRICAO, LOTE, VALIDADE, DATA_ENTRADA, HORA_ENTRADA, QUANTIDADE, PRECO, COD_FORN) VALUES ('PAPEL SULFITE', '524515', '2030/11/19','2024/11/19', '11:46:00', 1.000,25.35,1);
INSERT INTO TB_PRODUTOS (DESRICAO, LOTE, VALIDADE, DATA_ENTRADA, HORA_ENTRADA, QUANTIDADE, PRECO, COD_FORN) VALUES  ('TESOURA', '25548', '2050/12/25', '2023/10/11', '18:00:00', 200, 12.00,2);
INSERT INTO TB_PRODUTOS (DESRICAO, LOTE, VALIDADE, DATA_ENTRADA, HORA_ENTRADA, QUANTIDADE, PRECO, COD_FORN) VALUES ('CANETA ESFEROGRÁFICA AZUL', '55566', '2025/06/01', '2020/07/21','05:06:00', 100, 5.00, 10);
INSERT INTO TB_PRODUTOS (DESRICAO, LOTE, VALIDADE, DATA_ENTRADA, HORA_ENTRADA, QUANTIDADE, PRECO, COD_FORN) VALUES ('LÁPIS PRETO', '46698', '2021/12/17', '2019/01/01', '10:00:00', 1000, 1.50, 4);

--DELETAR UMA INSERÇÃO 
--DELETE FROM TB_PRODUTOS WHERE COD_FORN = 3

CREATE TABLE TB_VENDAS(
			COD_VENDA INT NOT NULL IDENTITY (1,1),
			VALOR DECIMAL (9,2),
			QUANTIDADE INT,
			PRECO DECIMAL,
			DATA_VENDA DATE,
			HORA_VENDA  TIME,
			COD_USU INT NOT NULL,
			COD_PROD INT NOT NULL,
			COD_CLI INT NOT NULL,
			COD_FORN INT NOT NULL,

			PRIMARY KEY (COD_VENDA),
			FOREIGN KEY (COD_USU) REFERENCES TB_USUARIOS (COD_USU),
			FOREIGN KEY (COD_PROD) REFERENCES TB_PRODUTOS,
			FOREIGN KEY (COD_CLI) REFERENCES TB_CLIENTES

);

INSERT INTO TB_VENDAS (VALOR, QUANTIDADE, PRECO, DATA_VENDA, HORA_VENDA, COD_USU, COD_PROD, COD_CLI, COD_FORN) VALUES (300.00, 200,1.5,'2024/10/01','12:00:00',1,1,1,4);
INSERT INTO TB_VENDAS (VALOR, QUANTIDADE, PRECO, DATA_VENDA, HORA_VENDA, COD_USU, COD_PROD, COD_CLI, COD_FORN) VALUES (2.535,100,25.35,'2024/09/21','08:10:00',2,2,2,1);
INSERT INTO TB_VENDAS (VALOR, QUANTIDADE, PRECO, DATA_VENDA, HORA_VENDA, COD_USU, COD_PROD, COD_CLI, COD_FORN) VALUES (200,100,2.00,'2023/11/13','18:50:00',3,3,3,2);
INSERT INTO TB_VENDAS (VALOR, QUANTIDADE, PRECO, DATA_VENDA, HORA_VENDA, COD_USU, COD_PROD, COD_CLI, COD_FORN) VALUES (750.00,150,5.00,'2021/08/22','11:50:00',4,3,3,3);